name: Run Test

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/setup-node@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with: 
          node-version: 18.13
      - name: Install Dependencies
        run: npm ci
      - name: Run tests
        run: npm test

